### ISSUE TITLE
Can't start a poll

### ISSUE THREAD

**Issue by akdor1154** [SLC3/MARS#112]
Clicking a poll should start it (it seems), in my case it does nothing. Looking into it, I'm using Ubuntu repo versions of Node, Mongo so this might be the first issue...

```
[2016-08-02 19:04:07.143]  ERROR    
stack:  MongoError: exception: the $unwind field path must be specified as a string
stack:      at Function.MongoError.create (/home/jarrad/src/MARS/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
stack:      at commandCallback (/home/jarrad/src/MARS/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:1187:66)
stack:      at Callbacks.emit (/home/jarrad/src/MARS/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:119:3)
stack:      at null.messageHandler (/home/jarrad/src/MARS/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:358:23)
stack:      at Socket.<anonymous> (/home/jarrad/src/MARS/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:292:22)
stack:      at emitOne (events.js:77:13)
stack:      at Socket.emit (events.js:169:7)
stack:      at readableAddChunk (_stream_readable.js:146:16)
stack:      at Socket.Readable.push (_stream_readable.js:110:10)
stack:      at TCP.onread (net.js:523:20)
error: {
error:   "name": "MongoError",
error:   "message": "exception: the $unwind field path must be specified as a string",
error:   "errmsg": "exception: the $unwind field path must be specified as a string",
error:   "code": 15981,
error:   "ok": 0
error: }
```

**Comment by akdor1154** [comment]
Yep, mongo was too old (insert creepy Meryn Trant pic here). Sorry!

**Comment by nathansherburn** [comment]
For anyone else coming across this issue,
Make sure you have a 64bit OS, and have installed [MongoDB](https://docs.mongodb.com/manual/installation/) 3.2+
